### PR TITLE
Basic template for course content for distribution

### PR DESCRIPTION
**Pull request by ateucher**
Added folder with data, script files, and a basic README.md. Most scripts are empty except for the first one, which I populated very minimally (though it may be enough as is). Feel free to rename/restructure/add/remove files that are for your content.

I started numbering the scripts at `01_` but in the course outline and bookdown, it is actually Chapter 5. Thoughts on numbering scheme?

Once we have this nailed we can create a zip out of this folder and point `usethis::use_course()` at it.

### CODE REVIEW

**Comment by ateucher** [comment]
Yes good call

**Comment by gcperk** [comment]
Looking good but I would keep the numbering in line with the chapter numbers. In that way when the participants save their work from chapter 1 and 2 they can label it 01_calculator etc.

**Comment by ateucher** [comment]
I'm good with that!

**Comment by ateucher** [comment]
☝️ @boshek @stephhazlitt @gcperk updated - also made README.md auto-generated from list of files to help make sure they are correct.

**Comment by gcperk** [comment]
Looks good - thanks Andy

**Pull request merged**
