### PR TITLE
update template order

### PR DESCRIPTION
**Pull request by boshek**
Does this look about right?

### CODE REVIEW

**Comment by stephhazlitt** [comment]
Are we supposed to be manually editing this [line](https://github.com/bcgov/ds-intro-to-r-2-day/blob/master/03-project-intro.Rmd#L19) in each `.Rmd`?

**Comment by ateucher** [comment]
@stephhazlitt yes. I tried to automate it but because the Rmd's are merged before they're rendered, there doesn't appear to be any way to get the episode number dynamically. (If it's a standalone document you can use `knitr::current_input()`).

**Comment by ateucher** [comment]
I think so! I wish the bookdown chapters aligned with the episode Rmds though!

**Comment by stephhazlitt** [comment]
On it!

**Pull request merged**
